apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-perl-mojolicious
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-perl-mojolicious
  template:
    metadata:
      labels:
        app: docker-perl-mojolicious
    spec:
      containers:
      - image: idock.daumkakao.io/bravo-gwak/docker-perl-mojolicious:latest
        imagePullPolicy: Always
        name: docker-perl-mojolicious
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: docker-perl-mojolicious
spec:
  selector:
    app: docker-perl-mojolicious
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 80
